### ISSUE TITLE
Broken link to some command line docs

### ISSUE THREAD

**Issue by bwentwor** [IBM-Bluemix-Docs/iam#1]
The "Commands for managing accounts, orgs, and roles" link just above the "Cloud Foundry access" heading points to https://console.stage1.bluemix.net/docs/cli/reference/bluemix_cli/bx_cli.html#bx_commands_acctorg

I don't think that is accessible outside of IBM. However, it is available on the production server when you remove "stage1."

**Comment by mekaufman** [comment]
Source fixed. Will close once I verify in a prod build.
