### ISSUE TITLE
Improve connection between IAM token and API key docs

### ISSUE THREAD

**Issue by sgraden** [IBM-Bluemix-Docs/iam#14]
Not sure the best way to do this, but our team is providing a way for users to see a generated REST API call based on the inputs they have entered into a form. This uses an IBM IAM Token and so we link them to this page https://console.bluemix.net/docs/iam/apikey_iamtoken.html#iamtoken_from_apikey. 

We then noticed that that docs page tells the user to do a CLI command that requires a platform API Key, but doesn't clearly indicate where to get that best. User MAY notice it in the left nav, but might as well provide a link to it in the paragraph. I see this being done on the other API key docs pages so I figure its okay.

Recommendation: 

{{site.data.keyword.Bluemix}} APIs can be accessed only by users that are authorized by an assigned IAM role. Therefore, the user that is calling the API must pass credentials for the API to authenticate. You can generate an IAM token by using either your personal or service ID's API key as described [here](https://console.bluemix.net/docs/iam/userid_keys.html#userapikey). This process is also used if you are developing an application that needs to work with other {{site.data.keyword.Bluemix_notm}} services. You must use a service ID API key to get an access token to be passed to each of the {{site.data.keyword.Bluemix_notm}} services.

Note I just inserted this link https://console.bluemix.net/docs/iam/userid_keys.html#userapikey into the "here" word. Guessing that was actually where it was intended to go.

**Comment by mekaufman** [comment]
@sgraden Thanks, Steve. I have made an update to the topic to link to both the service ID and user API keys topics.
