### ISSUE TITLE
Assign access to your SoftLayer account

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix-Docs/iam#18]
https://console.bluemix.net/docs/iam/mnginfra.html#managing-infrastructure-access

3. Select to Assign access to your SoftLayer account.

I do not have this option.

**Comment by mekaufman** [comment]
@rvennam Is your account linked and you have access to edit SoftLayer permissions? Both of those are requirements for seeing that tile on the choose which access you want to assign page.
