### ISSUE TITLE
502 Bad Gateway: Registered endpoint failed to handle the request. on login 

### ISSUE THREAD

**Issue by bdreamer** [IBM-Bluemix-Docs/iam#22]
I created an account (for testing) last Friday and am still getting this error message when trying to login at cloud.ibm.com/login. I enter my id & password (using fernemh@yahoo.com for ID). It actually logs me in but I have to know to go back to cloud.ibm.com to see my account. My w3 ID is fernehay@us.ibm.com

**Comment by mekaufman** [comment]
@bdreamer Thank you for your feedback and providing your w3 ID. I'm going to reach out with a technical contact that can help us look into your issue. Thanks.
