### ISSUE TITLE
welcome email

### ISSUE THREAD

**Issue by bdreamer** [IBM-Bluemix-Docs/iam#23]

**Comment by bdreamer** [comment]
my co-worker & i both created new accounts last friday but got very different welcome emails. we both registered at cloud.ibm.com/registration
arj.var92@gmail.com and fernemh@yahoo.com
<img width="709" alt="arjun-2" src="https://user-images.githubusercontent.com/18686652/54542172-4a646d00-4969-11e9-9e76-e87091022056.png">
![image](https://user-images.githubusercontent.com/18686652/54542199-594b1f80-4969-11e9-9aa2-a86c7724b507.png)

**Comment by renchaorevee** [comment]
pinged nipun.bayas@ibm.com to take a look

**Comment by cjcarpen** [comment]
Thanks for reporting this issue! We've deployed a fix so that only the correct email is shown. If you run into this problem in the future, please do report again!
