### ISSUE TITLE
Broken link to IAM AppID

### ISSUE THREAD

**Issue by mbirch-ca** [IBM-Bluemix-Docs/iam#24]
On this page near the bottom there's reference to how to integrate IAM with your web application

https://cloud.ibm.com/docs/iam?topic=iam-iamfaq#appid

When I click on this link it goes to a "page not found" as [the link points at this location](https://cloud.ibm.com/docs/services/appid?topic=appid-gettingstarted#gettingstarted)

**Comment by mekaufman** [comment]
@mbirch-ca Thank you for reporting. The link is fixed.
