### ISSUE TITLE
hyperlinks not working on Examples of how to use a service ID

### ISSUE THREAD

**Issue by bharaniabhishek123** [IBM-Bluemix-Docs/iam#28]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
hyperlinks not working inside section "Examples of how to use a service ID" on page
2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/iam?topic=iam-serviceids#examples_serviceid
3. Do you have a suggestion about how to resolve the issue?
An example on how to use the service id.

**Comment by mekaufman** [comment]
This has been fixed.
